const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Plugins.Touch,
		C3.Behaviors.solid,
		C3.Behaviors.Flash,
		C3.Behaviors.MoveTo,
		C3.Behaviors.lunarray_LiteTween,
		C3.Behaviors.Sin,
		C3.Behaviors.scrollto,
		C3.Behaviors.Bullet,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Rotate,
		C3.Behaviors.Fade,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.Particles,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.TiledBg.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Audio.Acts.Preload,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Touch.Cnds.OnTapGestureObject
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{TiledBackground: 0},
	{gravity: 0},
	{Player: 0},
	{Touch: 0},
	{touch_control: 0},
	{platform: 0},
	{Solid: 0},
	{block: 0},
	{block2: 0},
	{Flash: 0},
	{MoverA: 0},
	{Sprite3: 0},
	{LiteTween: 0},
	{Sprite4: 0},
	{spawn: 0},
	{Sine: 0},
	{Sprite5: 0},
	{ScrollTo: 0},
	{Camera: 0},
	{Bullet: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{sprite21sheet: 0},
	{sprite18sheet: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{LastScoreFont: 0},
	{Rotate: 0},
	{vverxsheet: 0},
	{destore: 0},
	{sprite23sheet: 0},
	{HighScoreFont: 0},
	{Fade: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{SpawnPIL: 0},
	{napravlenie: 0},
	{faerbol: 0},
	{block_faerbol: 0},
	{spawn_faerbol: 0},
	{Sprite12: 0},
	{TimeFont: 0},
	{PlusHP: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite23: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{GameResultsFont: 0},
	{efffect_black: 0},
	{effect_black_out: 0},
	{Audio: 0},
	{Browser: 0},
	{ArmazenamentoLocal: 0},
	{area: 0},
	{Parpadeo: 0},
	{continue: 0},
	{Seno: 0},
	{SinTítulo: 0},
	{Girar: 0},
	{confeti: 0},
	{Partículas: 0},
	{Sprite15: 0},
	{Partículas2: 0},
	{Partículas3: 0},
	{BestScore: 0},
	{BestMin: 0},
	{BestSec: 0},
	{Seconds: 0},
	{Minutes: 0},
	{HP: 0},
	{Score: 0},
	{speed: 0},
	{fon: 0},
	{sound: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Player: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	touch_control: class extends self.ISpriteInstance {},
	platform: class extends self.ITiledBackgroundInstance {},
	block: class extends self.ISpriteInstance {},
	block2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	spawn: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Camera: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	sprite21sheet: class extends self.ISpriteInstance {},
	sprite18sheet: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	LastScoreFont: class extends self.ISpriteFontInstance {},
	vverxsheet: class extends self.ISpriteInstance {},
	destore: class extends self.ISpriteInstance {},
	sprite23sheet: class extends self.ISpriteInstance {},
	HighScoreFont: class extends self.ISpriteFontInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	SpawnPIL: class extends self.ISpriteInstance {},
	faerbol: class extends self.ISpriteInstance {},
	block_faerbol: class extends self.ISpriteInstance {},
	spawn_faerbol: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	TimeFont: class extends self.ISpriteFontInstance {},
	PlusHP: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	GameResultsFont: class extends self.ISpriteFontInstance {},
	efffect_black: class extends self.ISpriteInstance {},
	effect_black_out: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	ArmazenamentoLocal: class extends self.IInstance {},
	area: class extends self.ISpriteInstance {},
	continue: class extends self.ISpriteInstance {},
	SinTítulo: class extends self.ISpriteInstance {},
	confeti: class extends self.ISpriteInstance {},
	Partículas: class extends self.IParticlesInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Partículas2: class extends self.IParticlesInstance {},
	Partículas3: class extends self.IParticlesInstance {}
}